require: rubocop-rails

# AllCops settings
AllCops:
  TargetRubyVersion: 2.7
  Include:
    - 'app/**/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'spec/**/*'

# Rails settings
Rails/Validation:
  Enabled: true

# Lint settings
Lint/UnusedMethodArgument:
  Enabled: false

# Style settings
Style/Documentation:
  Enabled: false