version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  rspec:
    build: .
    command: bash -c "bundle exec rake db:create db:migrate && bundle exec rspec"
    volumes:
      - .:/app
    depends_on:
      - db
  rubocop:
    build: .
    command: bundle exec rubocop -A
    volumes:
      - .:/app
    depends_on:
      - db